# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kris Payne
description: "Vastly experienced insurance leader looking to disect and understand retrospective performance, as well as developing predictive models for possible future outcomes, using my array of analytical skills. Please visit my Github & LinkedIn pages by using the links below to find out more on how I have contributed in driving a positive business impact using data!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Group Head of Data Analytics <span style="color:#f58506"> Portfolio </span>
location: "Leeds, UK"
avatar_image: /img/Profile_Pic_New Cropped.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/paynekris/" # Add your linkedln handle
github: "https://github.com/KrisPayne01"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

