# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kris Payne
description: "Hi I'm Kris, and I'm a keen Snr. Data Analytics and Scientist manager.  My portfolio focuses on interesting projects I've recently undertaken to showcase my skillset within numerous coding platforms, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Lead Data Analytics Manager <span style="color:#f58506"> Portfolio </span>
location: "Leeds, UK"
resume_url: /docs/Kris Payne_CV.docx
avatar_image: /img/Profile Pic.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/paynekris/" # Add your linkedln handle
github: "https://github.com/KrisPayne01"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

